"""add team founded year

Revision ID: cb4dd1ac276a
Revises: 0001
Create Date: 2026-09-26 14:24:04.064939
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb4dd1ac276a'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
